/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	         SC_Init.c
  * @author	 
  * @version 	
  * @date	
  * @brief	         
  * @details         Contains the MCU initialization function and its C file
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */

#include "SC_Init.h"	// MCU initialization header file, including all firmware library header files
#include "SCDriver_List.h"
#include "HeadFiles\SC_itExtern.h"



/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
/*************************************.Generated by EasyCodeCube.************************************/

/**
  * @brief MCU init
  * @note 
  * @param
  */
void SC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	SC_GPIO_Init();
	SC_OPTION_Init();
	SC_RCC_Init();
	SC_SYSTICK_Init();
	SC_DMA0_Init();
	SC_UART3_Init();
	SC_SPI1_Init();
	SC_TIM0_Init();
	SC_TIM5_Init();
	SC_TIM6_Init();
	SC_ADC_Init();
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief RCC init
  * @note 
  * @param
  */
void SC_RCC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	RCC_Unlock(0xFF);
	RCC_HXTCmd(DISABLE);
	RCC_LXTCmd(DISABLE);
	RCC_LIRCCmd(ENABLE);
	RCC_HIRCCmd(ENABLE);
	/*INTEN*/RCC_ITConfig(ENABLE);
	RCC_HIRCDIV1Cmd(ENABLE);
	RCC_SYSCLKConfig(RCC_SYSCLKSource_HIRC);
	RCC_HCLKConfig(RCC_SYSCLK_Div1);
	RCC_APB0Config(RCC_HCLK_Div1);
	RCC_APB0Cmd(ENABLE);
	RCC_APB1Config(RCC_HCLK_Div1);
	RCC_APB1Cmd(ENABLE);
	RCC_APB2Config(RCC_HCLK_Div1);
	RCC_APB2Cmd(ENABLE);
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief system timer init
  * @note 
  * @param
  */
void SC_SYSTICK_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	RCC_Unlock(0xFF);
	RCC_SystickCLKConfig(RCC_SysTickSource_HCLK_DIV8);
	RCC_SystickSetCounter(16000);
	NVIC_SetPriority(SysTick_IRQn,0);
	RCC_SystickCmd(ENABLE);
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief custom OPTION init
  * @note 
  * @param
  */
void SC_OPTION_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief nvic init
  * @note 
  * @param
  */
void SC_NVIC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief GPIO init
  * @note 
  * @param
  */
void SC_GPIO_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
    /*GPIOInit_PC01 Struct*/GPIO_InitTypeDef GPIOInit_PC01_Struct;
    GPIOInit_PC01_Struct.GPIO_Pin = GPIO_Pin_1;
    GPIOInit_PC01_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
    GPIOInit_PC01_Struct.GPIO_DriveLevel = 0;
    GPIO_Init(GPIOC,&GPIOInit_PC01_Struct);/*TK15端口初始化*/
    /*GPIOInit_PC02 Struct*/GPIO_InitTypeDef GPIOInit_PC02_Struct;
    GPIOInit_PC02_Struct.GPIO_Pin = GPIO_Pin_2;
    GPIOInit_PC02_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
    GPIOInit_PC02_Struct.GPIO_DriveLevel = 0;
    GPIO_Init(GPIOC,&GPIOInit_PC02_Struct);/*TK16端口初始化*/
    /*GPIOInit_PC03 Struct*/GPIO_InitTypeDef GPIOInit_PC03_Struct;
    GPIOInit_PC03_Struct.GPIO_Pin = GPIO_Pin_3;
    GPIOInit_PC03_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
    GPIOInit_PC03_Struct.GPIO_DriveLevel = 0;
    GPIO_Init(GPIOC,&GPIOInit_PC03_Struct);/*TK17端口初始化*/
    /*GPIOInit_PC04 Struct*/GPIO_InitTypeDef GPIOInit_PC04_Struct;
    GPIOInit_PC04_Struct.GPIO_Pin = GPIO_Pin_4;
    GPIOInit_PC04_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
    GPIOInit_PC04_Struct.GPIO_DriveLevel = 0;
    GPIO_Init(GPIOC,&GPIOInit_PC04_Struct);/*TK18端口初始化*/
    /*GPIOInit_PC05 Struct*/GPIO_InitTypeDef GPIOInit_PC05_Struct;
    GPIOInit_PC05_Struct.GPIO_Pin = GPIO_Pin_5;
    GPIOInit_PC05_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
    GPIOInit_PC05_Struct.GPIO_DriveLevel = 0;
    GPIO_Init(GPIOC,&GPIOInit_PC05_Struct);/*TK19端口初始化*/
    /*GPIOInit_PC06 Struct*/GPIO_InitTypeDef GPIOInit_PC06_Struct;
    GPIOInit_PC06_Struct.GPIO_Pin = GPIO_Pin_6;
    GPIOInit_PC06_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
    GPIOInit_PC06_Struct.GPIO_DriveLevel = 0;
    GPIO_Init(GPIOC,&GPIOInit_PC06_Struct);/*TK20端口初始化*/
    /*GPIOInit_PC07 Struct*/GPIO_InitTypeDef GPIOInit_PC07_Struct;
    GPIOInit_PC07_Struct.GPIO_Pin = GPIO_Pin_7;
    GPIOInit_PC07_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
    GPIOInit_PC07_Struct.GPIO_DriveLevel = 0;
    GPIO_Init(GPIOC,&GPIOInit_PC07_Struct);/*TK21端口初始化*/
    /*GPIOInit_PC08 Struct*/GPIO_InitTypeDef GPIOInit_PC08_Struct;
    GPIOInit_PC08_Struct.GPIO_Pin = GPIO_Pin_8;
    GPIOInit_PC08_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
    GPIOInit_PC08_Struct.GPIO_DriveLevel = 0;
    GPIO_Init(GPIOC,&GPIOInit_PC08_Struct);/*TK22端口初始化*/
	/*GPIOInit_PA06 Struct*/GPIO_InitTypeDef GPIOInit_PA06_Struct;
	GPIOInit_PA06_Struct.GPIO_Pin = GPIO_Pin_6;
	GPIOInit_PA06_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PA06_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA06_Struct);/*PA.06端口初始化*/
	/*GPIOInit_PB02 Struct*/GPIO_InitTypeDef GPIOInit_PB02_Struct;
	GPIOInit_PB02_Struct.GPIO_Pin = GPIO_Pin_2;
	GPIOInit_PB02_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB02_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB02_Struct);/*PB.02端口初始化*/
	/*GPIOInit_PB03 Struct*/GPIO_InitTypeDef GPIOInit_PB03_Struct;
	GPIOInit_PB03_Struct.GPIO_Pin = GPIO_Pin_3;
	GPIOInit_PB03_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB03_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB03_Struct);/*PB.03端口初始化*/
	/*GPIOInit_PB04 Struct*/GPIO_InitTypeDef GPIOInit_PB04_Struct;
	GPIOInit_PB04_Struct.GPIO_Pin = GPIO_Pin_4;
	GPIOInit_PB04_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB04_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB04_Struct);/*PB.04端口初始化*/
	/*GPIOInit_PB05 Struct*/GPIO_InitTypeDef GPIOInit_PB05_Struct;
	GPIOInit_PB05_Struct.GPIO_Pin = GPIO_Pin_5;
	GPIOInit_PB05_Struct.GPIO_Mode = GPIO_Mode_OUT_PP;
	GPIOInit_PB05_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB05_Struct);/*PB.05端口初始化*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART0 init
  * @note 
  * @param
  */
void SC_UART0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART1 init
  * @note 
  * @param
  */
void SC_UART1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART2 init
  * @note 
  * @param
  */
void SC_UART2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief UART3 init
  * @note 
  * @param
  */
void SC_UART3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	/*GPIOInit_PC12 Struct*/GPIO_InitTypeDef GPIOInit_PC12_Struct;
	GPIOInit_PC12_Struct.GPIO_Pin = GPIO_Pin_12;
	GPIOInit_PC12_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PC12_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOC,&GPIOInit_PC12_Struct);/*RxD3端口初始化*/
	/*GPIOInit_PC13 Struct*/GPIO_InitTypeDef GPIOInit_PC13_Struct;
	GPIOInit_PC13_Struct.GPIO_Pin = GPIO_Pin_13;
	GPIOInit_PC13_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PC13_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOC,&GPIOInit_PC13_Struct);/*TxD3端口初始化*/
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_UART3, ENABLE);
	/*Init Struct*/UART_InitTypeDef UART_InitStruct;
	UART_InitStruct.UART_ClockFrequency = 64000000;
	UART_InitStruct.UART_BaudRate = 115200;
	UART_InitStruct.UART_Mode =  UART_Mode_10B;
	UART_Init(UART3, &UART_InitStruct);
	/*INT_EN*/UART_ITConfig(UART3,UART_IT_EN,ENABLE);
	/*INT_TX*/UART_ITConfig(UART3,UART_IT_TX,DISABLE);
	/*INT_RX*/UART_ITConfig(UART3,UART_IT_RX,ENABLE);
	/*Init Struct*/NVIC_SetPriority(UART1_3_5_IRQn,1);/*UART1_3_5*/
	NVIC_EnableIRQ(UART1_3_5_IRQn);
	/*Init Struct*/UART_PinRemapConfig(UART3,UART_PinRemap_Default);
	UART_TXCmd(UART3,ENABLE);
	UART_RXCmd(UART3,ENABLE);
  /*<Generated by EasyCodeCube end>*/		
}



/**
  * @brief UART4 init
  * @note 
  * @param
  */
void SC_UART4_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART5 init
  * @note 
  * @param
  */
void SC_UART5_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief Timer0 init
  * @note 
  * @param
  */
void SC_TIM0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	RCC_APB0PeriphClockCmd(RCC_APB0Periph_TIM0,ENABLE);
	/*Init Struct*/TIM_TimeBaseInitTypeDef TIM_TimeBaseInitStruct;
	TIM_TimeBaseInitStruct.TIM_WorkMode = TIM_WorkMode_Timer;
	TIM_TimeBaseInitStruct.TIM_Prescaler = TIM_PRESCALER_1;
	TIM_TimeBaseInitStruct.TIM_CounterMode = TIM_CounterMode_Up;
	TIM_TimeBaseInitStruct.TIM_Preload = 1536;
	TIM_TimeBaseInitStruct.TIM_EXENX = TIM_EXENX_Disable;
	TIM_TIMBaseInit(TIM0, &TIM_TimeBaseInitStruct);
	/*Init Struct*/TIM_IC_InitTypeDef TIM_IC_InitStruct;
	TIM_IC_InitStruct.TIM_RICPIN = TIM_RICPin_Disable;
	TIM_IC_InitStruct.TIM_FICPIN = TIM_FICPin_Disable;
	TIM_ICInit(TIM0, &TIM_IC_InitStruct);
	TIM_ICCmd(TIM0, DISABLE);
	/*Init Struct*/TIM_PWM_InitTypeDef TIM_PWM_InitStruct;
	TIM_PWM_InitStruct.TIM_PWMOutputChannl = TIM_PWMChannel_Less;
	TIM_PWM_InitStruct.TIM_PWMLowPolarityChannl = TIM_PWMChannel_Less;
	TIM_PWMInit(TIM0, &TIM_PWM_InitStruct);
	TIM_PWMSetDuty(TIM0, TIM_PWMChannel_PWMB,50);
	/*PWMB Duty*/TIM_PWMSetDuty(TIM0, TIM_PWMChannel_PWMB,50);
	/*INTEN*/TIM_ITConfig(TIM0,TIM_IT_INTEN, ENABLE);
	/*TI*/TIM_ITConfig(TIM0,TIM_IT_TI,ENABLE);
	/*Init Struct*/NVIC_SetPriority(TIMER0_IRQn,3);/*TIMER0*/
	NVIC_EnableIRQ(TIMER0_IRQn);
	TIM_Cmd(TIM0,ENABLE);
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief Timer1 init
  * @note 
  * @param
  */
void SC_TIM1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer2 init
  * @note 
  * @param
  */
void SC_TIM2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer3 init
  * @note 
  * @param
  */
void SC_TIM3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}


/**
  * @brief Timer4 init
  * @note 
  * @param
  */
void SC_TIM4_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer5 init
  * @note 
  * @param
  */
void SC_TIM5_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM5, ENABLE);
	/*Init Struct*/TIM_TimeBaseInitTypeDef TIM_TimeBaseInitStruct;
	TIM_TimeBaseInitStruct.TIM_WorkMode = TIM_WorkMode_Timer;
	TIM_TimeBaseInitStruct.TIM_Prescaler = TIM_PRESCALER_2;
	TIM_TimeBaseInitStruct.TIM_CounterMode = TIM_CounterMode_Down_UP;
	TIM_TimeBaseInitStruct.TIM_Preload = 32768;
	TIM_TimeBaseInitStruct.TIM_EXENX = TIM_EXENX_Disable;
	TIM_TIMBaseInit(TIM5, &TIM_TimeBaseInitStruct);
	/*Init Struct*/TIM_IC_InitTypeDef TIM_IC_InitStruct;
	TIM_IC_InitStruct.TIM_RICPIN = TIM_RICPin_Tn;
	TIM_IC_InitStruct.TIM_FICPIN = TIM_FICPin_Tn;
	TIM_ICInit(TIM5, &TIM_IC_InitStruct);
	TIM_ICCmd(TIM5, ENABLE);
	TIM_PinRemapConfig(TIM5, TIM_PinRemap_Default);
	/*Init Struct*/TIM_PWM_InitTypeDef TIM_PWM_InitStruct;
	TIM_PWM_InitStruct.TIM_PWMOutputChannl = TIM_PWMChannel_Less;
	TIM_PWM_InitStruct.TIM_PWMLowPolarityChannl = TIM_PWMChannel_Less;
	TIM_PWMInit(TIM5, &TIM_PWM_InitStruct);
	TIM_PWMSetDuty(TIM5, TIM_PWMChannel_PWMA,50);
	/*PWMB Duty*/TIM_PWMSetDuty(TIM5, TIM_PWMChannel_PWMB,50);
	/*INTEN*/TIM_ITConfig(TIM5,TIM_IT_INTEN, ENABLE);
	/*EXR*/TIM_ITConfig(TIM5,TIM_IT_EXR,ENABLE);
	/*EXF*/TIM_ITConfig(TIM5,TIM_IT_EXF,ENABLE);
	/*TI*/TIM_ITConfig(TIM5,TIM_IT_TI,DISABLE);
	/*Init Struct*/NVIC_SetPriority(TIMER4_5_IRQn,2);/*TIMER4_5*/
	NVIC_EnableIRQ(TIMER4_5_IRQn);
	TIM_Cmd(TIM5,ENABLE);
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer6 init
  * @note 
  * @param
  */
void SC_TIM6_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM6, ENABLE);
	/*Init Struct*/TIM_TimeBaseInitTypeDef TIM_TimeBaseInitStruct;
	TIM_TimeBaseInitStruct.TIM_WorkMode = TIM_WorkMode_Timer;
	TIM_TimeBaseInitStruct.TIM_Prescaler = TIM_PRESCALER_2;
	TIM_TimeBaseInitStruct.TIM_CounterMode = TIM_CounterMode_Down_UP;
	TIM_TimeBaseInitStruct.TIM_Preload = 32768;
	TIM_TimeBaseInitStruct.TIM_EXENX = TIM_EXENX_Disable;
	TIM_TIMBaseInit(TIM6, &TIM_TimeBaseInitStruct);
	/*Init Struct*/TIM_IC_InitTypeDef TIM_IC_InitStruct;
	TIM_IC_InitStruct.TIM_RICPIN = TIM_RICPin_Tn;
	TIM_IC_InitStruct.TIM_FICPIN = TIM_FICPin_Tn;
	TIM_ICInit(TIM6, &TIM_IC_InitStruct);
	TIM_ICCmd(TIM6, ENABLE);
	TIM_PinRemapConfig(TIM6, TIM_PinRemap_Default);
	/*Init Struct*/TIM_PWM_InitTypeDef TIM_PWM_InitStruct;
	TIM_PWM_InitStruct.TIM_PWMOutputChannl = TIM_PWMChannel_Less;
	TIM_PWM_InitStruct.TIM_PWMLowPolarityChannl = TIM_PWMChannel_Less;
	TIM_PWMInit(TIM6, &TIM_PWM_InitStruct);
	TIM_PWMSetDuty(TIM6, TIM_PWMChannel_PWMA,50);
	/*PWMB Duty*/TIM_PWMSetDuty(TIM6, TIM_PWMChannel_PWMB,50);
	/*INTEN*/TIM_ITConfig(TIM6,TIM_IT_INTEN, ENABLE);
	/*EXR*/TIM_ITConfig(TIM6,TIM_IT_EXR,ENABLE);
	/*EXF*/TIM_ITConfig(TIM6,TIM_IT_EXF,ENABLE);
	/*TI*/TIM_ITConfig(TIM6,TIM_IT_TI,DISABLE);
	/*CAPR*/TIM_DMACmd(TIM6,TIM_DMAReq_CAPR,ENABLE);
	/*CAPF*/TIM_DMACmd(TIM6,TIM_DMAReq_CAPF,DISABLE);
	/*TI*/TIM_DMACmd(TIM6,TIM_DMAReq_TI,DISABLE);
	/*Init Struct*/NVIC_SetPriority(TIMER6_7_IRQn,2);/*TIMER6_7*/
	NVIC_EnableIRQ(TIMER6_7_IRQn);
	TIM_Cmd(TIM6,ENABLE);
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer7 init
  * @note 
  * @param
  */
void SC_TIM7_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}



/**
  * @brief PWM0 init
  * @note 
  * @param
  */
void SC_PWM0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}



/**
  * @brief LEDPWM init
  * @note 
  * @param
  */
void SC_LEDPWM_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}


/**
  * @brief INT init
  * @note 
  * @param
  */
void SC_INT_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief ADC init
  * @note 
  * @param
  */
void SC_ADC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	/*Init Struct*/ADC_InitTypeDef ADC_Base_InitStruct;
	ADC_Base_InitStruct.ADC_ConvMode = ADC_ConvMode_Single;
	ADC_Base_InitStruct.ADC_Prescaler = ADC_Prescaler_32CLOCK;
	ADC_Base_InitStruct.ADC_EAIN = ADC_EAIN_Less|ADC_EAIN_0|ADC_EAIN_1|ADC_EAIN_10|ADC_EAIN_11|ADC_EAIN_12|ADC_EAIN_13|ADC_EAIN_14|ADC_EAIN_15;
	ADC_Base_InitStruct.ADC_VREF = ADC_VREF_VDD;
	ADC_Init(ADC, &ADC_Base_InitStruct);
	ADC_SetChannel(ADC,ADC_Channel_10);
	/*ADCIF*/ADC_ITConfig(ADC,ADC_IT_ADCIF, ENABLE);
	ADC_DMACmd(ADC,DISABLE);
	/*Init Struct*/NVIC_SetPriority(ADC_IRQn,3);/*ADC*/
	NVIC_EnableIRQ(ADC_IRQn);
	ADC_Cmd(ADC,ENABLE);
  /*<Generated by EasyCodeCube end>*/
}



/**
  * @brief VREF init
  * @note 
  * @param
  */
void SC_VREF_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DAC init
  * @note 
  * @param
  */
void SC_DAC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief TemperSensor init
  * @note 
  * @param
  */
void SC_TemperSensor_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief PCAP init
  * @note 
  * @param
  */
void SC_PCAP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief EPWM init
  * @note 
  * @param
  */
void SC_EPWM_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}





/**
  * @brief OP init
  * @note 
  * @param
  */
void SC_OP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}



/**
  * @brief OP0 init
  * @note 
  * @param
  */
void SC_OP0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}
/**
  * @brief OP1 init
  * @note 
  * @param
  */
void SC_OP1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief OP2 init
  * @note 
  * @param
  */
void SC_OP2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}



/**
  * @brief QEP0 init
  * @note 
  * @param
  */
void SC_QEP0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief QEP1 init
  * @note 
  * @param
  */
void SC_QEP1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}




/**
  * @brief CAN init
  * @note 
  * @param
  */
void SC_CAN_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief IAP init
  * @note 
  * @param
  */
void SC_IAP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief SPI0 init
  * @note 
  * @param
  */
void SC_SPI0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief SPI1 init
  * @note 
  * @param
  */
void SC_SPI1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	/*GPIOInit_PB00 Struct*/GPIO_InitTypeDef GPIOInit_PB00_Struct;
	GPIOInit_PB00_Struct.GPIO_Pin = GPIO_Pin_0;
	GPIOInit_PB00_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PB00_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB00_Struct);/*MOSI1端口初始化*/
	/*GPIOInit_PB01 Struct*/GPIO_InitTypeDef GPIOInit_PB01_Struct;
	GPIOInit_PB01_Struct.GPIO_Pin = GPIO_Pin_1;
	GPIOInit_PB01_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PB01_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOB,&GPIOInit_PB01_Struct);/*MISO1端口初始化*/
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_QTWI1, ENABLE);
	/*Init Struct*/SPI_InitTypeDef SPI_InitStruct;
	SPI_InitStruct.SPI_FirstBit = SPI_FirstBit_MSB;
	SPI_InitStruct.SPI_Mode = SPI_Mode_Master;
	SPI_InitStruct.SPI_CPOL = SPI_CPOL_Low;
	SPI_InitStruct.SPI_CPHA = SPI_CPHA_1Edge;
	SPI_InitStruct.SPI_Prescaler = SPI_Prescaler_1;
	SPI_InitStruct.SPI_DataSize = SPI_DataSize_8B;
	SPI_Init(SPI1, &SPI_InitStruct);
	SPI_PinRemapConfig(SPI1,SPI_PinRemap_Default);
	/*INTEN*/SPI_ITConfig(SPI1,SPI_IT_INTEN, DISABLE);
	/*DMA_RX*/SPI_DMACmd(SPI1,SPI_DMAReq_RX,ENABLE);
	/*DMA_TX*/SPI_DMACmd(SPI1,SPI_DMAReq_TX,ENABLE);
	SPI_Cmd(SPI1,ENABLE);
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief SPI2 init
  * @note 
  * @param
  */
void SC_SPI2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief SPI3 init
  * @note
  * @param
  */
void SC_SPI3_Init(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief TWI0 init
  * @note 
  * @param
  */
void SC_TWI0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief TWI1 init
  * @note 
  * @param
  */
void SC_TWI1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief TWI2 init
  * @note
  * @param
  */
void SC_TWI2_Init(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief TWI3 init
  * @note
  * @param
  */
void SC_TWI3_Init(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief BTM init
  * @note 
  * @param
  */
void SC_BTM_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief CRC init
  * @note 
  * @param
  */
void SC_CRC_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA0 init
  * @note 
  * @param
  */
void SC_DMA0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
	RCC_AHBPeriphClockCmd(RCC_AHBPeriph_DMA,ENABLE);
	/*Init Struct*/DMA_InitTypeDef DMA_InitStruct;
	DMA_InitStruct.DMA_Priority = DMA_Priority_LOW;
	DMA_InitStruct.DMA_TargetMode = DMA_TargetMode_FIXED;
	DMA_InitStruct.DMA_SourceMode = DMA_SourceMode_FIXED;
	DMA_InitStruct.DMA_SrcAddress = 0x0000;
	DMA_InitStruct.DMA_DstAddress = 0x0000;
	DMA_InitStruct.DMA_DataSize = DMA_DataSize_Byte;
	DMA_InitStruct.DMA_Burst = DMA_Burst_Disable;
	DMA_InitStruct.DMA_Request = DMA_Request_Null;
	DMA_InitStruct.DMA_BufferSize = 0x0000;
	DMA_InitStruct.DMA_CircularMode = DMA_CircularMode_Disable;
	DMA_Init(DMA0, &DMA_InitStruct);
	/*INTEN*/DMA_ITConfig(DMA0,DMA_IT_INTEN, DISABLE);
	DMA_DMACmd(DMA0,DMA_DMAReq_CHRQ,DISABLE);
	DMA_Cmd(DMA0,DISABLE);
  /*<Generated by EasyCodeCube end>*/
}

extern uint16_t ADC_ValueArray[ADC_VALUE_NUM];
/**
  * @brief DMA1 init
  * @note 
  * @param
  */
void SC_DMA1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief DMA2 init
  * @note 
  * @param
  */
void SC_DMA2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA3 init
  * @note 
  * @param
  */
void SC_DMA3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/
}


/**
  * @brief WDT init
  * @note 
  * @param
  */
void SC_WDT_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief PWR init
  * @note 
  * @param
  */
void SC_PWR_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief LCD init
  * @note 
  * @param
  */

void SC_LCD_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC LED Init
  * @note 
  * @param
  */
void SC_LED_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}



/**
  * @brief SC MR Init
  * @note 
  * @param
  */
void SC_MR_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}



/**
  * @brief SC ACMP Init
  * @note 
  * @param
  */
void SC_ACMP_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/		
}



/**
  * @brief SC ACMP0 Init
  * @note 
  * @param
  */
void SC_ACMP0_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC ACMP1 Init
  * @note 
  * @param
  */
void SC_ACMP1_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC ACMP2 Init
  * @note 
  * @param
  */
void SC_ACMP2_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC ACMP3 Init
  * @note 
  * @param
  */
void SC_ACMP3_Init(void)
{
  /*<Generated by EasyCodeCube begin>*/
  /*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief SC QSPI0 Init
  * @note
  * @param
  */
void SC_QSPI0_Init(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}

/**
  * @brief SC QSPI1 Init
  * @note
  * @param
  */
void SC_QSPI1_Init(void)
{
    /*<Generated by EasyCodeCube begin>*/
    /*<Generated by EasyCodeCube end>*/
}
