/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	SysFunVarDefine.h
  * @author	 
  * @version 	
  * @date	
  * @brief	Store var control and function control extern
  * @details 
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */
#ifndef SYS_FUN_VAR_DEFINE
    #define SYS_FUN_VAR_DEFINE
#include "CustomType.h"
#include "UserExport.h"
#include "FunctionType.h"
#include "CompCtrlDefine.h"
#endif
#include "stdint.h"
#include "core_cm0plus.h"
/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!

/*************************************.Generated by EasyCodeCube.************************************/
extern volatile unsigned char DMA_SPI_FLAG;
extern volatile uint16_t UI_DisplayTime_1st;
extern volatile uint16_t UI_DisplayTime_2nd;

extern void ChangeTouchKeyvalue(void);
extern void Sys_Scan(void);
extern void IcResourceInit(void);
